# Generated by Django 4.0.3 on 2022-03-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_title_post_file_type_remove_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='file',
        ),
    ]
